
import './globals.css'
/*import '@/components/navbar/Navbar.css'*/
import Providers from "./Providers";
import Navbar from "@/components/navbar/Navbar";
import { dataNavbar } from '@/utils/get-data';

export const metadata = {
  title: 'Learn languages',
  description: 'Generated by Anthony',
}
export const revalidate = 3600;
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
const items = await dataNavbar();

  return (
		<html lang="en">
			<body>
				<main className="bg-background flex flex-col items-center">
					<Providers>
						{" "}
						<Navbar props={items} /> {children}{" "}
					</Providers>
				</main>
			</body>
		</html>
	);
}
