import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/navbar/Navbar";
import { fetchDataALL } from "@/utils/get-data";

export const metadata = {
	title: "Learn languages",
	description: "Generated by Anthony",
};

export const revalidate = 3600;

export default async function RootLayout({
											 children,
										 }: {
	children: React.ReactNode;
}) {
	const [navData] = await fetchDataALL();

	return (
		<html lang="en" data-theme="blue" suppressHydrationWarning>
		<body>
		<main className="bg-background flex flex-col items-center">
			<Providers>
				<Navbar props={navData} />
				{children}
			</Providers>
		</main>
		</body>
		</html>
	);
}
